[lofi]
"lofi hip hop radio ğŸ“š - beats to relax/study to" = "https://www.youtube.com/watch?v=jfKfPfyJRdk"
"lofi hip hop radio â€“ beats to sleep/study/relax to â˜•" = "https://www.youtube.com/watch?v=rPjez8z61rI"
"synthwave radio ğŸŒŒ - beats to chill/game to" = "https://www.youtube.com/watch?v=4xDzrJKXOOY"
"Thursday vibes ğŸ€ Calm Your Mind ~ Lofi hip hop mix - Lofi music for sleep/study/relax/aesthetic" = "https://www.youtube.com/watch?v=7lrSWL-iJkg"
[music]
"Melodies for coding | Focus & Chill from devaslife" = "https://www.youtube.com/watch?v=VUVPkoByTn4"
"We Lost the Sea - Departure Song" = "https://www.youtube.com/watch?v=SBOVkptjJhE"