[lofi]
"lofi hip hop radio ğŸ“š - beats to relax/study to" = "https://www.youtube.com/watch?v=jfKfPfyJRdk"
"lofi hip hop radio â€“ beats to sleep/study/relax to â˜•" = "https://www.youtube.com/watch?v=rPjez8z61rI"
"synthwave radio ğŸŒŒ - beats to chill/game to" = "https://www.youtube.com/watch?v=4xDzrJKXOOY"
"Thursday vibes ğŸ€ Calm Your Mind ~ Lofi hip hop mix - Lofi music for sleep/study/relax/aesthetic" = "https://www.youtube.com/watch?v=7lrSWL-iJkg"
[music]
"Never Gonna Give You UP" = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
"An unsuccessful example" = ""